name: config-loader ci
on: [push, pull_request]

jobs:
  gcc-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: setup gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11

      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: build
        run: |
          mkdir build
          CXX=g++ cmake -H. -Bbuild
          cmake --build build
      - name: test
        run: |
          cd build/bin
          ./config_loader_test

  clang-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: setup clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13

      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: build
        run: |
          mkdir build
          CXX=clang++ cmake -H. -Bbuild
          cmake --build build
      - name: test
        run: |
          cd build/bin
          ./config_loader_test
